### ISSUE TITLE
devkit build native-ios failed

### ISSUE THREAD

**Issue by tuanna222** [gameclosure/native-ios#23]
[build]    [error]  build failed
        [build]    [error]  TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at Object.exports.copySplash (/Users/tuanna222/Desktop/www/devkit2/newproject/modules/devkit-core/modules/native-ios/lib/copyResources.js:57:32)
    at SuperGroup.xcodeProject.installModule.frameworks (/Users/tuanna222/Desktop/www/devkit2/newproject/modules/devkit-core/modules/native-ios/build.js:213:19)
    at SuperGroup._execNextStep (/Users/tuanna222/Desktop/www/devkit2/newproject/modules/devkit-core/modules/native-ios/node_modules/ff/lib/ff.js:348:10)
    at Group.done (/Users/tuanna222/Desktop/www/devkit2/newproject/modules/devkit-core/modules/native-ios/node_modules/ff/lib/ff.js:65:17)
    at /Users/tuanna222/Desktop/www/devkit2/newproject/modules/devkit-core/modules/native-ios/node_modules/ff/lib/ff.js:132:34
    at pbxProject.<anonymous> (/Users/tuanna222/Desktop/www/devkit2/newproject/modules/devkit-core/modules/native-ios/lib/xcodeUtil.js:44:7)
    at pbxProject.emit (events.js:98:17)
    at pbxProject.<anonymous> (/Users/tuanna222/Desktop/www/devkit2/newproject/modules/devkit-core/modules/native-ios/node_modules/xcode/lib/pbxProject.js:30:18)
    at ChildProcess.emit (events.js:98:17)
        [build]    8.42 seconds elapsed

**Comment by collingreen** [comment]
Fixed in https://github.com/gameclosure/native-ios/commit/a574ca25a8e96bfcef279d4a049c03be81829449
